### PR TITLE
Save settings

### PR DESCRIPTION
**Pull request by inki2**
Settings are now saved to file and read during startup. If no settings file is found during startup, one will be created from default values.

### CODE REVIEW

**Comment by inki2** [comment]
@rhomspuron This PR is dependant on PR #12 .

**Comment by marceloalcocer** [comment]
@inki2 I've been testing v0.3.0 at the MAX IV CoSAXS beamline, and no configuration file seems to be created if missing. Could you confirm this please?

**Comment by inki2** [comment]
@marceloalcocer The file is created but not the hardcoded folder IcepapOSC. That is by design and will change when @rhomspuron has decided how the setup implementation should work. For now the user will have to manually create the folder for the ini-file.

**Comment by rhomspuron** [comment]
hi @inki2,

Sorry for the delay. I will integrate this PR and start with the py3 - qt5 migration. @marceloalcocer I will investigate the configuration file that is needed and propose one solution.

**Pull request merged**
