### PR TITLE
Ported MaxIV changes to Python3 QT5

### PR DESCRIPTION
**Pull request by valerixb**
Ported MaxIV changes to Python 3, QT5
Updated MaxIV to latest Alba master and resolved conflicts
flake8 check is now passed with 0 errors
Fixed an inconsistency in time display between X axis and cursor when local time is different from UTC
Tested in MaxIV for ~1 month

This pull request supersedes old #17

### CODE REVIEW

**Comment by rhomspuron** [comment]
Hi @valerixb, 

Thanks for the migration!

I did a fast review and I propose to do some change: 
 * Do not use compiled ui file and load on execution time
 * Remove all commented code
 * Reorganize the ui folder

I can do this changes and update the PR. 

On the other hand, it is not possible to do backup outside IcepapCMS. The logic was moved to it, and it is not more on icepap library. In this case we should remove the backup from the Oscilloscope application.

**Comment by valerixb** [comment]
Hi @rhomspuron 
   Thank you very much for your review and quick response! 
Yes, the compiled UI: I tried, but I was not able to dynamically load the GUI because of the custom buttons and I did not know how to manage the search paths; I am grateful that you fix that (I'm still a rookie at my age ahahahahah). Thank you also for reorganizing the UI folder and stripping the unnecessary comments!
OK with the backup: we'll do them with IcepapCMS instead.
Thank you; best regards.

**Comment by rhomspuron** [comment]
Hi @valerixb 
I tried to export the signal configuration and it generates an error: 
```
Traceback (most recent call last):
  File "/homelocal/rhoms/develop/pycharm/IcepapOSC/icepaposc/window_main.py", line 527, in _export_signal_set
    with open(fname[0], 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: ''
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 5553, resource id: 41965847, major code: 40 (TranslateCoords), minor code: 0

```
I will solve it, but what do you think to create and default files to have custom configuration and load automatically? 
The file can be on ~/.icepaposc/customsignal.yaml. In this case the export/import signals buttons change the logic to add/remove custom signal.

**Comment by valerixb** [comment]
Hi @rhomspuron 
Sorry for not catching that and thank you for fixing. We would actually prefer to choose the file to load/save, as in our facility the same linux filesystem is mounted on all beamlines, so we'd have to change the .icepaposc/customsignal.yaml manually; anyway, the final decision is yours, of course.
Thanks; best regards

**Comment by rhomspuron** [comment]
> Hi @rhomspuron
> Sorry for not catching that and thank you for fixing. We would actually prefer to choose the file to load/save, as in our facility the same linux filesystem is mounted on all beamlines, so we'd have to change the .icepaposc/customsignal.yaml manually; anyway, the final decision is yours, of course.
> Thanks; best regards

This is a good point, and what do you think to have in the setting where to put this file, like in IcepapCMS you can configure where to save the firmware or other configuration? In this way we will have one file where we put all the custom configuration with specific names and in the case that you have this file on the storage you only need to change were load the file on the settings.

**Comment by valerixb** [comment]
OK, Roberto. Thank you

**Pull request merged**
