### PR TITLE
MaxIV Kits-HW mods july2020

### PR DESCRIPTION
**Pull request by valerixb**
Hi
At MaxIV Synchrotron we made some modifications:
- possibility to change color/marker/line for each signal
- different background colors
- additional buttons for easier navigation with trackball
- possibility to export/import custom signal sets
- save signals to file
- add a scale/offset to a signal
This is the version we currently use at the facility. Do you think it can be of interest to pull it into the main Alba master branch?

### CODE REVIEW

**Comment by rhomspuron** [comment]
Hi @valerixb, 

Thanks for the PR!. 

Could you solve the conflicts with the master branch? In this way I can do the merge.

**Comment by rhomspuron** [comment]
Hi @valerixb 

I tried to run the application and it is not compatible with python 3 and qt5. In addition the errors of the CI are generated by the flake8 verification. 

I'm merging your branch on the commit (https://github.com/ALBA-Synchrotron/IcepapOSC/pull/17/commits/1b299071908738b30439a2105ebe65e3f6e8587a) with and I will do it a PR to your branch. Could you reset your branch to this commit?

**Comment by valerixb** [comment]
Hi!
  yes: I missed the migration to py3 and qt5; I'm currently working on a new branch (py36): https://github.com/valerixb/IcepapOSC/tree/py36 
to port our changes to the new versions, but then we'll have to test it, before merging. So thanks, I will merge your PR and then open another PR after proper testing in our facility. Thank you!

**Comment by rhomspuron** [comment]
Hi @valerixb 

I saw on the code that you use the icepap.backup module, this is obsolete. We move the module to the IcepapCMS. 
Do you need to do a backup?

**Comment by rhomspuron** [comment]
Hi @valerixb 

I did the merge and some some problems: https://github.com/ALBA-Synchrotron/IcepapOSC/tree/kits_mods_july2020, 

We can work on this branch to finish the migration.

**Comment by valerixb** [comment]
Yes: the backup was explicitly requested by some users. We also had some talks as to what leave to IcePAPCMS, but, for example, also Status and ESYNC were requested to be available in the OSC, so I added them. I was also asked to comment out the auto save option. I understand that this customization might not be the best for everyone at every facility, but I created the PR in case you found interesting the code that we wrote for the added functionality: signal sets, line appearance/marker, etc. - mainly cosmetic changes, but maybe useful to someone else. We can anyway keep this as a separate branch, eg "MaxIV_custom", if you think it's better. 
Thank you; I'll get back to you as soon as I finish the port to py3/qt5.

**Comment by valerixb** [comment]
Hi. I updated MaxIV version and ported it to python 3, QT5. It is now able to be merged to Alba master; I opened another pull request (#18 ), so this one is now superseded and can be disregarded and  closed. Thank you.

**Comment by rhomspuron** [comment]
Hi @valerixb, thanks for doing it. I will close this PR and review #18

**Pull request closed without merging**
